-- create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email");
-- create "sessions" table
CREATE TABLE "sessions"
(
    "id"            bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sid"           character varying NOT NULL,
    "expiry"        timestamptz       NOT NULL,
    "deleted"       boolean           NOT NULL DEFAULT false,
    "user_sessions" bigint            NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("user_sessions") REFERENCES "users" ("id") ON DELETE SET NULL
);
-- create index "sessions_sid_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_sid_key" ON "sessions" ("sid");
