version: "3.9"
services:
  starter-api:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - PROJECT_NAME=${PROJECT_NAME:-nodummy}
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ${PWD:-.}:/home/${PROJECT_NAME}