version: "3.9"
services:
  gqlgen-starter-api:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - PROJECT_NAME=${PROJECT_NAME:-nodummy}
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ${PWD:-.}:/home/${PROJECT_NAME}
    depends_on:
      - gqlgen-starter-api-db
  gqlgen-starter-api-db:
    image: postgres:13-alpine
    container_name: gqlgen-starter-api-db
    hostname: gqlgenstarterapidb
    ports:
      - "5432:5432"
    env_file: .env
