version: "3.9"
services:
  api:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-api
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - PROJECT_NAME=${PROJECT_NAME:-nodummy}
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ${PWD:-.}:/home/${PROJECT_NAME}
    depends_on:
      - postgresdb
      - redisdb
  postgresdb:
    image: postgres:13-alpine
    container_name: ${PROJECT_NAME}-postgresdb
    hostname: postgresdb
    ports:
      - ${DEVELOPMENTDB_PORT}
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgresdb
  postgrestestdb:
    image: postgres:13-alpine
    container_name: ${PROJECT_NAME}-testdb
    hostname: postgrestestdb
    ports:
      - "5678:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgrestestdb
  redisdb:
    image: redis:7.2-alpine
    hostname: redisdb
    container_name: ${PROJECT_NAME}-redis
    ports:
      - ${REDIS_PORT}
  nats:
    image: nats:latest
    hostname: nats
    container_name: ${PROJECT_NAME}-nats
    entrypoint: "/nats-server"
    command: "-js -m 5555"
    ports:
      - 4222:4222
      - 5555:5555