version: "3.9"
services:
  starter-api:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - PROJECT_NAME=${PROJECT_NAME:-nodummy}
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ${PWD:-.}:/home/${PROJECT_NAME}
    depends_on:
      - starter-db
  starter-db:
    image: postgres:13-alpine
    container_name: starter-db
    hostname: starter-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: starter-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST: starter-db
