// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gqlgen-starter/internal/ent/schema"
	"gqlgen-starter/internal/ent/session"
	"gqlgen-starter/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSid is the schema descriptor for sid field.
	sessionDescSid := sessionFields[0].Descriptor()
	// session.SidValidator is a validator for the "sid" field. It is called by the builders before save.
	session.SidValidator = sessionDescSid.Validators[0].(func(string) error)
	// sessionDescDeleted is the schema descriptor for deleted field.
	sessionDescDeleted := sessionFields[2].Descriptor()
	// session.DefaultDeleted holds the default value on creation for the deleted field.
	session.DefaultDeleted = sessionDescDeleted.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
