package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"encoding/json"
	"gqlgen-starter/cmd/build"
	"gqlgen-starter/internal/gql/generated"
)

// Hello is the resolver for the hello field.
func (r *mutationResolver) Hello(ctx context.Context) (string, error) {
	return "Hello world", nil
}

// HealthCheck is the resolver for the healthCheck field.
func (r *queryResolver) HealthCheck(ctx context.Context) (interface{}, error) {
	jsonResponse, _ := json.Marshal(map[string]interface{}{
		"Version": build.BuildVersion,
		"Commit":  build.BuildCommit,
		"Time":    build.BuildTime,
	})
	return jsonResponse, nil
}

// Mutation returns generated1.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
