# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: '1.21'

    - name: Build
      run: touch .env && make build

    - name: Lint
      run: |
        touch .env
        go install honnef.co/go/tools/cmd/staticcheck@latest
        make lint

    - name: Test
      run: touch .env && make test
